export const EMAILJS_SERVICE_ID = "YOUR_SERVICE_ID";
export const EMAILJS_TEMPLATE_ID = "YOUR_TEMPLATE_ID";
export const EMAILJS_PUBLIC_KEY = "YOUR_PUBLIC_KEY";
// export const EMAILJS_WHATSAPP_NUMBER ="WHATSAPP_NUMBER";
export const WHATSAPP_NUMBER = '919986515115';